/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftMenu: typeof import('./src/components/LeftMenu.vue')['default']
    ModelParamsPanel: typeof import('./src/components/ModelParamsPanel.vue')['default']
    ModelRunConfigPanel: typeof import('./src/components/ModelRunConfigPanel.vue')['default']
    ModelRunPanel: typeof import('./src/components/ModelRunPanel.vue')['default']
    ParamConfigPanel: typeof import('./src/components/ParamConfigPanel.vue')['default']
    ResultAnalysisPanel: typeof import('./src/components/ResultAnalysisPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunMonitorPanel: typeof import('./src/components/RunMonitorPanel.vue')['default']
    ScenarioEvaluationDialog: typeof import('./src/components/ScenarioEvaluationDialog.vue')['default']
    ScenarioEvaluationModal: typeof import('./src/components/ScenarioEvaluationModal.vue')['default']
    ScenarioEvaluationPanel: typeof import('./src/components/ScenarioEvaluationPanel.vue')['default']
    ScenarioPanel: typeof import('./src/components/ScenarioPanel.vue')['default']
    WaterDataPanel: typeof import('./src/components/WaterDataPanel.vue')['default']
  }
}
